### ISSUE TITLE
后端控制路由时，addroute方法为什么要添加一维数组路由

### ISSUE THREAD

**Issue by destiny516** [lyt-Top/vue-next-admin#22]
后端控制路由时，addroute方法为什么要添加一维数组路由，为什么要做这一步处理
`/**
 * 添加动态路由
 * @method router.addRoute
 * @description 此处循环为 dynamicRoutes（/@/router/route）第一个顶级 children 的路由一维数组，非多级嵌套
 * @link 参考：https://next.router.vuejs.org/zh/api/#addroute
 */
export async function setAddRoute() {
	await setFilterRouteEnd().forEach((route: RouteRecordRaw) => {
		router.addRoute(route);
	});
}`

**Comment by zcvvvbb** [comment]
因为只有一个router-view
